//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5Updater2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S5Updater2.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything patched.
        /// </summary>
        public static string AllPatched {
            get {
                return ResourceManager.GetString("AllPatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert HE to Gold.
        /// </summary>
        public static string ConvertHE {
            get {
                return ResourceManager.GetString("ConvertHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        public static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string DevMode {
            get {
                return ResourceManager.GetString("DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Mode.
        /// </summary>
        public static string EasyMode {
            get {
                return ResourceManager.GetString("EasyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please look at the log. If you don&apos;t know what to do, copy&amp;paste it when asking for help..
        /// </summary>
        public static string ErrorDetected {
            get {
                return ResourceManager.GetString("ErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold: .
        /// </summary>
        public static string GoldPath {
            get {
                return ResourceManager.GetString("GoldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcuts to extra1 &amp; extra2 on desktop?.
        /// </summary>
        public static string HEEditor_CreateLinks {
            get {
                return ResourceManager.GetString("HEEditor_CreateLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Mapeditor.
        /// </summary>
        public static string HEFixEditor {
            get {
                return ResourceManager.GetString("HEFixEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE: .
        /// </summary>
        public static string HEPath {
            get {
                return ResourceManager.GetString("HEPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Map.
        /// </summary>
        public static string InstallMap {
            get {
                return ResourceManager.GetString("InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to: .
        /// </summary>
        public static string Log_AllowAccess {
            get {
                return ResourceManager.GetString("Log_AllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map installed: .
        /// </summary>
        public static string Log_InstallMap {
            get {
                return ResourceManager.GetString("Log_InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPack installed: .
        /// </summary>
        public static string Log_InstallModPack {
            get {
                return ResourceManager.GetString("Log_InstallModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set LuaDebugger enabled: .
        /// </summary>
        public static string Log_SetDebuggerEnabled {
            get {
                return ResourceManager.GetString("Log_SetDebuggerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dev Mode to: .
        /// </summary>
        public static string Log_SetDev {
            get {
                return ResourceManager.GetString("Log_SetDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gold path to: .
        /// </summary>
        public static string Log_SetGoldPath {
            get {
                return ResourceManager.GetString("Log_SetGoldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gold Registry path to: .
        /// </summary>
        public static string Log_SetGoldReg {
            get {
                return ResourceManager.GetString("Log_SetGoldReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set HE path to: .
        /// </summary>
        public static string Log_SetHEPath {
            get {
                return ResourceManager.GetString("Log_SetHEPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set CppLogic enabled: .
        /// </summary>
        public static string Log_SetHookEnabled {
            get {
                return ResourceManager.GetString("Log_SetHookEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Intro Video to: .
        /// </summary>
        public static string Log_SetIntroVideo {
            get {
                return ResourceManager.GetString("Log_SetIntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language to: .
        /// </summary>
        public static string Log_SetLang {
            get {
                return ResourceManager.GetString("Log_SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Resolution to: .
        /// </summary>
        public static string Log_SetReso {
            get {
                return ResourceManager.GetString("Log_SetReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapPacks:.
        /// </summary>
        public static string MapPacks {
            get {
                return ResourceManager.GetString("MapPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping:.
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps:.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPacks:.
        /// </summary>
        public static string ModPacks {
            get {
                return ResourceManager.GetString("ModPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths:.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating CppLogic.
        /// </summary>
        public static string Prog_CppL_Validating {
            get {
                return ResourceManager.GetString("Prog_CppL_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating LuaDebugger.
        /// </summary>
        public static string Prog_Debugger_Updating {
            get {
                return ResourceManager.GetString("Prog_Debugger_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no change needed.
        /// </summary>
        public static string Prog_GRel_NoChange {
            get {
                return ResourceManager.GetString("Prog_GRel_NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patching.
        /// </summary>
        public static string Prog_GRel_Patching {
            get {
                return ResourceManager.GetString("Prog_GRel_Patching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading patch.
        /// </summary>
        public static string Prog_U105_DownloadPatch {
            get {
                return ResourceManager.GetString("Prog_U105_DownloadPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening a browser window for download. Please execute, if it finishes, then press OK..
        /// </summary>
        public static string Prog_U105_MsgPatch {
            get {
                return ResourceManager.GetString("Prog_U105_MsgPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful: .
        /// </summary>
        public static string Prog_U105_Successful {
            get {
                return ResourceManager.GetString("Prog_U105_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing patch, waiting for it to finish....
        /// </summary>
        public static string Prog_U105_WaitForExec {
            get {
                return ResourceManager.GetString("Prog_U105_WaitForExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching exe.
        /// </summary>
        public static string Prog_U106_Copy {
            get {
                return ResourceManager.GetString("Prog_U106_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download exe patch.
        /// </summary>
        public static string Prog_U106_Download {
            get {
                return ResourceManager.GetString("Prog_U106_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really override registry?.
        /// </summary>
        public static string ReallyOverrideRegistry {
            get {
                return ResourceManager.GetString("ReallyOverrideRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry:.
        /// </summary>
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gold installation folder.
        /// </summary>
        public static string SelectGold {
            get {
                return ResourceManager.GetString("SelectGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select HE installation folder.
        /// </summary>
        public static string SelectHE {
            get {
                return ResourceManager.GetString("SelectHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set registry.
        /// </summary>
        public static string SetRegistry {
            get {
                return ResourceManager.GetString("SetRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        public static string SettingsBottom {
            get {
                return ResourceManager.GetString("SettingsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show intro video.
        /// </summary>
        public static string ShowIntro {
            get {
                return ResourceManager.GetString("ShowIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string TabMain {
            get {
                return ResourceManager.GetString("TabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string TabMaps {
            get {
                return ResourceManager.GetString("TabMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying he installation.
        /// </summary>
        public static string TaskConvert_CopyingInstall {
            get {
                return ResourceManager.GetString("TaskConvert_CopyingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data patch.
        /// </summary>
        public static string TaskConvert_DownloadFileData {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading fonts.
        /// </summary>
        public static string TaskConvert_DownloadFont {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching data.
        /// </summary>
        public static string TaskConvert_PatchData {
            get {
                return ResourceManager.GetString("TaskConvert_PatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching fonts.
        /// </summary>
        public static string TaskConvert_PatchFont {
            get {
                return ResourceManager.GetString("TaskConvert_PatchFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcuts to game on desktop?.
        /// </summary>
        public static string TaskConvert_QstLink {
            get {
                return ResourceManager.GetString("TaskConvert_QstLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcuts to mapeditor on desktop?.
        /// </summary>
        public static string TaskConvert_QstLinkEditor {
            get {
                return ResourceManager.GetString("TaskConvert_QstLinkEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use Russian as language?.
        /// </summary>
        public static string TaskConvert_QstRu {
            get {
                return ResourceManager.GetString("TaskConvert_QstRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip patching Fonts? Patching Fonts causes UI errors when using Russian as language and is required for other languages..
        /// </summary>
        public static string TaskConvert_QstRuFull {
            get {
                return ResourceManager.GetString("TaskConvert_QstRuFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gold Registry path to: .
        /// </summary>
        public static string TaskConvert_QstSetReg {
            get {
                return ResourceManager.GetString("TaskConvert_QstSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiping fonts.
        /// </summary>
        public static string TaskConvert_SkipFont {
            get {
                return ResourceManager.GetString("TaskConvert_SkipFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking out.
        /// </summary>
        public static string TaskMPMap_Checkout {
            get {
                return ResourceManager.GetString("TaskMPMap_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found, cloning.
        /// </summary>
        public static string TaskMPMap_Cloning {
            get {
                return ResourceManager.GetString("TaskMPMap_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copying files.
        /// </summary>
        public static string TaskMPMap_CopyFiles {
            get {
                return ResourceManager.GetString("TaskMPMap_CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting changes.
        /// </summary>
        public static string TaskMPMap_DirtyDeleting {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! changes in repo, but chosen to keep.
        /// </summary>
        public static string TaskMPMap_DirtyKeep {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changes in {0}, delete?.
        /// </summary>
        public static string TaskMPMap_ErrDirty {
            get {
                return ResourceManager.GetString("TaskMPMap_ErrDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found, fetching.
        /// </summary>
        public static string TaskMPMap_Fetch {
            get {
                return ResourceManager.GetString("TaskMPMap_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest commit: .
        /// </summary>
        public static string TaskMPMap_LatestComm {
            get {
                return ResourceManager.GetString("TaskMPMap_LatestComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling repo: .
        /// </summary>
        public static string TaskMPMap_Repo {
            get {
                return ResourceManager.GetString("TaskMPMap_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating MP maps and scripts.
        /// </summary>
        public static string TaskMPMap_Start {
            get {
                return ResourceManager.GetString("TaskMPMap_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written UserScript to {0}.
        /// </summary>
        public static string TaskUserScript_WriteLog {
            get {
                return ResourceManager.GetString("TaskUserScript_WriteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from 1.05.
        /// </summary>
        public static string Update105 {
            get {
                return ResourceManager.GetString("Update105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 10 Fix.
        /// </summary>
        public static string Update106 {
            get {
                return ResourceManager.GetString("Update106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CppLogic.
        /// </summary>
        public static string UpdateCppLogic {
            get {
                return ResourceManager.GetString("UpdateCppLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update LuaDebugger.
        /// </summary>
        public static string UpdateDebugger {
            get {
                return ResourceManager.GetString("UpdateDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update MapPacks.
        /// </summary>
        public static string UpdateMapPacks {
            get {
                return ResourceManager.GetString("UpdateMapPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserScript:.
        /// </summary>
        public static string UserScript {
            get {
                return ResourceManager.GetString("UserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Color:.
        /// </summary>
        public static string UserScriptColor {
            get {
                return ResourceManager.GetString("UserScriptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string UserScriptZoom {
            get {
                return ResourceManager.GetString("UserScriptZoom", resourceCulture);
            }
        }
    }
}
