//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5Updater2 {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("S5Updater2.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TabMain {
            get {
                return ResourceManager.GetString("TabMain", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string SetRegistry {
            get {
                return ResourceManager.GetString("SetRegistry", resourceCulture);
            }
        }
        
        public static string GoldPath {
            get {
                return ResourceManager.GetString("GoldPath", resourceCulture);
            }
        }
        
        public static string HEPath {
            get {
                return ResourceManager.GetString("HEPath", resourceCulture);
            }
        }
        
        public static string SelectGold {
            get {
                return ResourceManager.GetString("SelectGold", resourceCulture);
            }
        }
        
        public static string SelectHE {
            get {
                return ResourceManager.GetString("SelectHE", resourceCulture);
            }
        }
        
        public static string Log_SetGoldPath {
            get {
                return ResourceManager.GetString("Log_SetGoldPath", resourceCulture);
            }
        }
        
        public static string Log_SetHEPath {
            get {
                return ResourceManager.GetString("Log_SetHEPath", resourceCulture);
            }
        }
        
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        public static string Log_SetGoldReg {
            get {
                return ResourceManager.GetString("Log_SetGoldReg", resourceCulture);
            }
        }
        
        public static string ReallyOverrideRegistry {
            get {
                return ResourceManager.GetString("ReallyOverrideRegistry", resourceCulture);
            }
        }
        
        public static string EasyMode {
            get {
                return ResourceManager.GetString("EasyMode", resourceCulture);
            }
        }
        
        public static string Update105 {
            get {
                return ResourceManager.GetString("Update105", resourceCulture);
            }
        }
        
        public static string Update106 {
            get {
                return ResourceManager.GetString("Update106", resourceCulture);
            }
        }
        
        public static string UpdateMapPacks {
            get {
                return ResourceManager.GetString("UpdateMapPacks", resourceCulture);
            }
        }
        
        public static string UpdateCppLogic {
            get {
                return ResourceManager.GetString("UpdateCppLogic", resourceCulture);
            }
        }
        
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        public static string AllPatched {
            get {
                return ResourceManager.GetString("AllPatched", resourceCulture);
            }
        }
        
        public static string Prog_U106_Download {
            get {
                return ResourceManager.GetString("Prog_U106_Download", resourceCulture);
            }
        }
        
        public static string Prog_U106_Copy {
            get {
                return ResourceManager.GetString("Prog_U106_Copy", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string ErrorDetected {
            get {
                return ResourceManager.GetString("ErrorDetected", resourceCulture);
            }
        }
        
        public static string Prog_U105_MsgPatch {
            get {
                return ResourceManager.GetString("Prog_U105_MsgPatch", resourceCulture);
            }
        }
        
        public static string Prog_U105_DownloadPatch {
            get {
                return ResourceManager.GetString("Prog_U105_DownloadPatch", resourceCulture);
            }
        }
        
        public static string Prog_U105_Successful {
            get {
                return ResourceManager.GetString("Prog_U105_Successful", resourceCulture);
            }
        }
        
        public static string Prog_U105_WaitForExec {
            get {
                return ResourceManager.GetString("Prog_U105_WaitForExec", resourceCulture);
            }
        }
        
        public static string Prog_GRel_NoChange {
            get {
                return ResourceManager.GetString("Prog_GRel_NoChange", resourceCulture);
            }
        }
        
        public static string Prog_GRel_Patching {
            get {
                return ResourceManager.GetString("Prog_GRel_Patching", resourceCulture);
            }
        }
        
        public static string Prog_CppL_Validating {
            get {
                return ResourceManager.GetString("Prog_CppL_Validating", resourceCulture);
            }
        }
        
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Log_SetLang {
            get {
                return ResourceManager.GetString("Log_SetLang", resourceCulture);
            }
        }
        
        public static string Log_SetReso {
            get {
                return ResourceManager.GetString("Log_SetReso", resourceCulture);
            }
        }
        
        public static string DevMode {
            get {
                return ResourceManager.GetString("DevMode", resourceCulture);
            }
        }
        
        public static string Log_SetDev {
            get {
                return ResourceManager.GetString("Log_SetDev", resourceCulture);
            }
        }
        
        public static string Log_SetIntroVideo {
            get {
                return ResourceManager.GetString("Log_SetIntroVideo", resourceCulture);
            }
        }
        
        public static string ShowIntro {
            get {
                return ResourceManager.GetString("ShowIntro", resourceCulture);
            }
        }
        
        public static string UpdateDebugger {
            get {
                return ResourceManager.GetString("UpdateDebugger", resourceCulture);
            }
        }
        
        public static string Prog_Debugger_Updating {
            get {
                return ResourceManager.GetString("Prog_Debugger_Updating", resourceCulture);
            }
        }
        
        public static string Log_SetDebuggerEnabled {
            get {
                return ResourceManager.GetString("Log_SetDebuggerEnabled", resourceCulture);
            }
        }
        
        public static string Log_SetHookEnabled {
            get {
                return ResourceManager.GetString("Log_SetHookEnabled", resourceCulture);
            }
        }
        
        public static string ConvertHE {
            get {
                return ResourceManager.GetString("ConvertHE", resourceCulture);
            }
        }
        
        public static string TaskConvert_SkipFont {
            get {
                return ResourceManager.GetString("TaskConvert_SkipFont", resourceCulture);
            }
        }
        
        public static string TaskConvert_QstSetReg {
            get {
                return ResourceManager.GetString("TaskConvert_QstSetReg", resourceCulture);
            }
        }
        
        public static string TaskConvert_QstRuFull {
            get {
                return ResourceManager.GetString("TaskConvert_QstRuFull", resourceCulture);
            }
        }
        
        public static string TaskConvert_QstRu {
            get {
                return ResourceManager.GetString("TaskConvert_QstRu", resourceCulture);
            }
        }
        
        public static string TaskConvert_QstLinkEditor {
            get {
                return ResourceManager.GetString("TaskConvert_QstLinkEditor", resourceCulture);
            }
        }
        
        public static string TaskConvert_QstLink {
            get {
                return ResourceManager.GetString("TaskConvert_QstLink", resourceCulture);
            }
        }
        
        public static string TaskConvert_PatchFont {
            get {
                return ResourceManager.GetString("TaskConvert_PatchFont", resourceCulture);
            }
        }
        
        public static string TaskConvert_PatchData {
            get {
                return ResourceManager.GetString("TaskConvert_PatchData", resourceCulture);
            }
        }
        
        public static string TaskConvert_DownloadFont {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFont", resourceCulture);
            }
        }
        
        public static string TaskConvert_DownloadFileData {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFileData", resourceCulture);
            }
        }
        
        public static string TaskConvert_CopyingInstall {
            get {
                return ResourceManager.GetString("TaskConvert_CopyingInstall", resourceCulture);
            }
        }
        
        public static string TaskMPMap_Checkout {
            get {
                return ResourceManager.GetString("TaskMPMap_Checkout", resourceCulture);
            }
        }
        
        public static string TaskMPMap_Cloning {
            get {
                return ResourceManager.GetString("TaskMPMap_Cloning", resourceCulture);
            }
        }
        
        public static string TaskMPMap_CopyFiles {
            get {
                return ResourceManager.GetString("TaskMPMap_CopyFiles", resourceCulture);
            }
        }
        
        public static string TaskMPMap_DirtyDeleting {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyDeleting", resourceCulture);
            }
        }
        
        public static string TaskMPMap_DirtyKeep {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyKeep", resourceCulture);
            }
        }
        
        public static string TaskMPMap_ErrDirty {
            get {
                return ResourceManager.GetString("TaskMPMap_ErrDirty", resourceCulture);
            }
        }
        
        public static string TaskMPMap_Fetch {
            get {
                return ResourceManager.GetString("TaskMPMap_Fetch", resourceCulture);
            }
        }
        
        public static string TaskMPMap_LatestComm {
            get {
                return ResourceManager.GetString("TaskMPMap_LatestComm", resourceCulture);
            }
        }
        
        public static string TaskMPMap_Repo {
            get {
                return ResourceManager.GetString("TaskMPMap_Repo", resourceCulture);
            }
        }
        
        public static string TaskMPMap_Start {
            get {
                return ResourceManager.GetString("TaskMPMap_Start", resourceCulture);
            }
        }
        
        public static string TabMaps {
            get {
                return ResourceManager.GetString("TabMaps", resourceCulture);
            }
        }
        
        public static string HEFixEditor {
            get {
                return ResourceManager.GetString("HEFixEditor", resourceCulture);
            }
        }
        
        public static string HEEditor_CreateLinks {
            get {
                return ResourceManager.GetString("HEEditor_CreateLinks", resourceCulture);
            }
        }
        
        public static string TaskUserScript_WriteLog {
            get {
                return ResourceManager.GetString("TaskUserScript_WriteLog", resourceCulture);
            }
        }
        
        public static string UserScriptColor {
            get {
                return ResourceManager.GetString("UserScriptColor", resourceCulture);
            }
        }
        
        public static string UserScriptZoom {
            get {
                return ResourceManager.GetString("UserScriptZoom", resourceCulture);
            }
        }
        
        public static string UserScript {
            get {
                return ResourceManager.GetString("UserScript", resourceCulture);
            }
        }
        
        public static string InstallMap {
            get {
                return ResourceManager.GetString("InstallMap", resourceCulture);
            }
        }
        
        public static string Log_InstallMap {
            get {
                return ResourceManager.GetString("Log_InstallMap", resourceCulture);
            }
        }
        
        public static string Log_InstallModPack {
            get {
                return ResourceManager.GetString("Log_InstallModPack", resourceCulture);
            }
        }
        
        public static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SettingsBottom {
            get {
                return ResourceManager.GetString("SettingsBottom", resourceCulture);
            }
        }
        
        public static string MapPacks {
            get {
                return ResourceManager.GetString("MapPacks", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        public static string ModPacks {
            get {
                return ResourceManager.GetString("ModPacks", resourceCulture);
            }
        }
        
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        public static string Log_AllowAccess {
            get {
                return ResourceManager.GetString("Log_AllowAccess", resourceCulture);
            }
        }
        
        public static string UpdateDebugger_VSCAdaptor {
            get {
                return ResourceManager.GetString("UpdateDebugger_VSCAdaptor", resourceCulture);
            }
        }
        
        public static string Prog_Debugger_Extension {
            get {
                return ResourceManager.GetString("Prog_Debugger_Extension", resourceCulture);
            }
        }
        
        public static string Prog_Debugger_Extension_Into {
            get {
                return ResourceManager.GetString("Prog_Debugger_Extension_Into", resourceCulture);
            }
        }
        
        public static string WinePrefix {
            get {
                return ResourceManager.GetString("WinePrefix", resourceCulture);
            }
        }
        
        public static string SelectWine {
            get {
                return ResourceManager.GetString("SelectWine", resourceCulture);
            }
        }
        
        public static string Log_SetWine {
            get {
                return ResourceManager.GetString("Log_SetWine", resourceCulture);
            }
        }
    }
}
