//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S5Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold: .
        /// </summary>
        internal static string Lbl_Gold {
            get {
                return ResourceManager.GetString("Lbl_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Edition: .
        /// </summary>
        internal static string Lbl_HE {
            get {
                return ResourceManager.GetString("Lbl_HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Lbl_Reso {
            get {
                return ResourceManager.GetString("Lbl_Reso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed map .
        /// </summary>
        internal static string Log_InstallMap {
            get {
                return ResourceManager.GetString("Log_InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Gold registry to: .
        /// </summary>
        internal static string Log_RegGold {
            get {
                return ResourceManager.GetString("Log_RegGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set LuaDebugger enabled: .
        /// </summary>
        internal static string Log_SetDebuggerEnabled {
            get {
                return ResourceManager.GetString("Log_SetDebuggerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dev Mode to: .
        /// </summary>
        internal static string Log_SetDev {
            get {
                return ResourceManager.GetString("Log_SetDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold install location set to: .
        /// </summary>
        internal static string Log_SetGold {
            get {
                return ResourceManager.GetString("Log_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE install location set to: .
        /// </summary>
        internal static string Log_SetHE {
            get {
                return ResourceManager.GetString("Log_SetHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set CppLogic enabled: .
        /// </summary>
        internal static string Log_SetHookEnabled {
            get {
                return ResourceManager.GetString("Log_SetHookEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language to: .
        /// </summary>
        internal static string Log_SetLang {
            get {
                return ResourceManager.GetString("Log_SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Resolution to: .
        /// </summary>
        internal static string Log_SetReso {
            get {
                return ResourceManager.GetString("Log_SetReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set show intro video to: .
        /// </summary>
        internal static string Log_SetVideo {
            get {
                return ResourceManager.GetString("Log_SetVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new updater version available. update?.
        /// </summary>
        internal static string Qst_UpdateUpdater {
            get {
                return ResourceManager.GetString("Qst_UpdateUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Status_Ok {
            get {
                return ResourceManager.GetString("Status_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying he installation.
        /// </summary>
        internal static string TaskConvert_CopyingInstall {
            get {
                return ResourceManager.GetString("TaskConvert_CopyingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data patch.
        /// </summary>
        internal static string TaskConvert_DownloadFileData {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading fonts.
        /// </summary>
        internal static string TaskConvert_DownloadFont {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching data.
        /// </summary>
        internal static string TaskConvert_PatchData {
            get {
                return ResourceManager.GetString("TaskConvert_PatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching fonts.
        /// </summary>
        internal static string TaskConvert_PatchFont {
            get {
                return ResourceManager.GetString("TaskConvert_PatchFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use Russian as language?.
        /// </summary>
        internal static string TaskConvert_QstRu {
            get {
                return ResourceManager.GetString("TaskConvert_QstRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip patching Fonts? Patching Fonts causes UI errors when using Russian as language and is required for other languages..
        /// </summary>
        internal static string TaskConvert_QstRuFull {
            get {
                return ResourceManager.GetString("TaskConvert_QstRuFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gold Registry path to: .
        /// </summary>
        internal static string TaskConvert_QstSetReg {
            get {
                return ResourceManager.GetString("TaskConvert_QstSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiping fonts.
        /// </summary>
        internal static string TaskConvert_SkipFont {
            get {
                return ResourceManager.GetString("TaskConvert_SkipFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating LuaDebugger.
        /// </summary>
        internal static string TaskDebugger_Updating {
            get {
                return ResourceManager.GetString("TaskDebugger_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no change needed.
        /// </summary>
        internal static string TaskHook_Ok {
            get {
                return ResourceManager.GetString("TaskHook_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patching.
        /// </summary>
        internal static string TaskHook_Patching {
            get {
                return ResourceManager.GetString("TaskHook_Patching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating CppLogic.
        /// </summary>
        internal static string TaskHook_Validating {
            get {
                return ResourceManager.GetString("TaskHook_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking out.
        /// </summary>
        internal static string TaskMPMap_Checkout {
            get {
                return ResourceManager.GetString("TaskMPMap_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found, cloning.
        /// </summary>
        internal static string TaskMPMap_Cloning {
            get {
                return ResourceManager.GetString("TaskMPMap_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copying files.
        /// </summary>
        internal static string TaskMPMap_CopyFiles {
            get {
                return ResourceManager.GetString("TaskMPMap_CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting changes.
        /// </summary>
        internal static string TaskMPMap_DirtyDeleting {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! changes in repo, but chosen to keep.
        /// </summary>
        internal static string TaskMPMap_DirtyKeep {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changes in {0}, delete?.
        /// </summary>
        internal static string TaskMPMap_ErrDirty {
            get {
                return ResourceManager.GetString("TaskMPMap_ErrDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found, fetching.
        /// </summary>
        internal static string TaskMPMap_Fetch {
            get {
                return ResourceManager.GetString("TaskMPMap_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest commit: .
        /// </summary>
        internal static string TaskMPMap_LatestComm {
            get {
                return ResourceManager.GetString("TaskMPMap_LatestComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling repo: .
        /// </summary>
        internal static string TaskMPMap_Repo {
            get {
                return ResourceManager.GetString("TaskMPMap_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating MP maps and scripts.
        /// </summary>
        internal static string TaskMPMap_Start {
            get {
                return ResourceManager.GetString("TaskMPMap_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading patch.
        /// </summary>
        internal static string TaskUpdate105_DownloadPatch {
            get {
                return ResourceManager.GetString("TaskUpdate105_DownloadPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing external patcher, please follow its UI..
        /// </summary>
        internal static string TaskUpdate105_MsgPatch {
            get {
                return ResourceManager.GetString("TaskUpdate105_MsgPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful: .
        /// </summary>
        internal static string TaskUpdate105_Successful {
            get {
                return ResourceManager.GetString("TaskUpdate105_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing patch, waiting for it to finish....
        /// </summary>
        internal static string TaskUpdate105_WaitForExec {
            get {
                return ResourceManager.GetString("TaskUpdate105_WaitForExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading exe patch.
        /// </summary>
        internal static string TaskUpdate106_DownloadFileExe {
            get {
                return ResourceManager.GetString("TaskUpdate106_DownloadFileExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching exe.
        /// </summary>
        internal static string TaskUpdate106_PatchExe {
            get {
                return ResourceManager.GetString("TaskUpdate106_PatchExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Development Tools.
        /// </summary>
        internal static string Title_GoldDev {
            get {
                return ResourceManager.GetString("Title_GoldDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Edition.
        /// </summary>
        internal static string TitleConvert {
            get {
                return ResourceManager.GetString("TitleConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Location.
        /// </summary>
        internal static string TitleInstallation {
            get {
                return ResourceManager.GetString("TitleInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S5 Updater .
        /// </summary>
        internal static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string TitleReg {
            get {
                return ResourceManager.GetString("TitleReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string TitleUpdate {
            get {
                return ResourceManager.GetString("TitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch required.
        /// </summary>
        internal static string Txt_AllPatchedNO {
            get {
                return ResourceManager.GetString("Txt_AllPatchedNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch OK.
        /// </summary>
        internal static string Txt_AllPatchedOK {
            get {
                return ResourceManager.GetString("Txt_AllPatchedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mappacks.
        /// </summary>
        internal static string Txt_Btn_UpdateMappacks {
            get {
                return ResourceManager.GetString("Txt_Btn_UpdateMappacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert HE to Gold.
        /// </summary>
        internal static string Txt_Convert {
            get {
                return ResourceManager.GetString("Txt_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string Txt_DebuggerActive {
            get {
                return ResourceManager.GetString("Txt_DebuggerActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        internal static string Txt_DevMode {
            get {
                return ResourceManager.GetString("Txt_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy mode.
        /// </summary>
        internal static string Txt_EasyMode {
            get {
                return ResourceManager.GetString("Txt_EasyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string Txt_EnableHook {
            get {
                return ResourceManager.GetString("Txt_EnableHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please show at the log. If you don&apos;t know what to do, copy&amp;paste it when asking for help..
        /// </summary>
        internal static string Txt_ErrMsg {
            get {
                return ResourceManager.GetString("Txt_ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.
        /// </summary>
        internal static string Txt_Extra0 {
            get {
                return ResourceManager.GetString("Txt_Extra0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fogland.
        /// </summary>
        internal static string Txt_Extra1 {
            get {
                return ResourceManager.GetString("Txt_Extra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legends.
        /// </summary>
        internal static string Txt_Extra2 {
            get {
                return ResourceManager.GetString("Txt_Extra2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set registry.
        /// </summary>
        internal static string Txt_GoldSetReg {
            get {
                return ResourceManager.GetString("Txt_GoldSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install map.
        /// </summary>
        internal static string Txt_InstallMap {
            get {
                return ResourceManager.GetString("Txt_InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Txt_Langua {
            get {
                return ResourceManager.GetString("Txt_Langua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  into .
        /// </summary>
        internal static string Txt_MapInto {
            get {
                return ResourceManager.GetString("Txt_MapInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen resolution requires Developent mode, enable?.
        /// </summary>
        internal static string Txt_QuestEnableDevModeRes {
            get {
                return ResourceManager.GetString("Txt_QuestEnableDevModeRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry already set, override?.
        /// </summary>
        internal static string Txt_QuestOverrideReg {
            get {
                return ResourceManager.GetString("Txt_QuestOverrideReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Txt_SetGold {
            get {
                return ResourceManager.GetString("Txt_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show intro video.
        /// </summary>
        internal static string Txt_ShowIntro {
            get {
                return ResourceManager.GetString("Txt_ShowIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show log.
        /// </summary>
        internal static string Txt_ShowLog {
            get {
                return ResourceManager.GetString("Txt_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Txt_TabPageGeneral {
            get {
                return ResourceManager.GetString("Txt_TabPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Txt_TabPageMaps {
            get {
                return ResourceManager.GetString("Txt_TabPageMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserScript.
        /// </summary>
        internal static string Txt_TabPageUserscript {
            get {
                return ResourceManager.GetString("Txt_TabPageUserscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win 10 Fix.
        /// </summary>
        internal static string Txt_Update106 {
            get {
                return ResourceManager.GetString("Txt_Update106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update LuaDebugger.
        /// </summary>
        internal static string Txt_UpdateDebugger {
            get {
                return ResourceManager.GetString("Txt_UpdateDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from 1.05.
        /// </summary>
        internal static string Txt_UpdateFrom105 {
            get {
                return ResourceManager.GetString("Txt_UpdateFrom105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update CppLogic.
        /// </summary>
        internal static string Txt_UpdateHook {
            get {
                return ResourceManager.GetString("Txt_UpdateHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update MP maps.
        /// </summary>
        internal static string Txt_UpdateMP {
            get {
                return ResourceManager.GetString("Txt_UpdateMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Color:.
        /// </summary>
        internal static string Txt_UserScriptColor {
            get {
                return ResourceManager.GetString("Txt_UserScriptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Txt_UserScriptZoom {
            get {
                return ResourceManager.GetString("Txt_UserScriptZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} file version infos.
        /// </summary>
        internal static string Txt_VersionCheckCount {
            get {
                return ResourceManager.GetString("Txt_VersionCheckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Version: {0} with {1}.
        /// </summary>
        internal static string Txt_VersioncheckDone {
            get {
                return ResourceManager.GetString("Txt_VersioncheckDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full version check.
        /// </summary>
        internal static string Txt_VersionCheckGold {
            get {
                return ResourceManager.GetString("Txt_VersionCheckGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full version check:.
        /// </summary>
        internal static string Txt_VersionCheckStart {
            get {
                return ResourceManager.GetString("Txt_VersionCheckStart", resourceCulture);
            }
        }
    }
}
