//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S5Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die done ähnelt.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gold:  ähnelt.
        /// </summary>
        internal static string Lbl_Gold {
            get {
                return ResourceManager.GetString("Lbl_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History Edition:  ähnelt.
        /// </summary>
        internal static string Lbl_HE {
            get {
                return ResourceManager.GetString("Lbl_HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        /// </summary>
        internal static string Lbl_Reso {
            get {
                return ResourceManager.GetString("Lbl_Reso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed map  ähnelt.
        /// </summary>
        internal static string Log_InstallMap {
            get {
                return ResourceManager.GetString("Log_InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changed Gold registry to:  ähnelt.
        /// </summary>
        internal static string Log_RegGold {
            get {
                return ResourceManager.GetString("Log_RegGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Dev Mode to:  ähnelt.
        /// </summary>
        internal static string Log_SetDev {
            get {
                return ResourceManager.GetString("Log_SetDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gold install location set to:  ähnelt.
        /// </summary>
        internal static string Log_SetGold {
            get {
                return ResourceManager.GetString("Log_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HE install location set to:  ähnelt.
        /// </summary>
        internal static string Log_SetHE {
            get {
                return ResourceManager.GetString("Log_SetHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set hook enabled:  ähnelt.
        /// </summary>
        internal static string Log_SetHookEnabled {
            get {
                return ResourceManager.GetString("Log_SetHookEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Language to:  ähnelt.
        /// </summary>
        internal static string Log_SetLang {
            get {
                return ResourceManager.GetString("Log_SetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Resolution to:  ähnelt.
        /// </summary>
        internal static string Log_SetReso {
            get {
                return ResourceManager.GetString("Log_SetReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set show intro video to:  ähnelt.
        /// </summary>
        internal static string Log_SetVideo {
            get {
                return ResourceManager.GetString("Log_SetVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new updater version available. update? ähnelt.
        /// </summary>
        internal static string Qst_UpdateUpdater {
            get {
                return ResourceManager.GetString("Qst_UpdateUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid ähnelt.
        /// </summary>
        internal static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string Status_Ok {
            get {
                return ResourceManager.GetString("Status_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copying he installation ähnelt.
        /// </summary>
        internal static string TaskConvert_CopyingInstall {
            get {
                return ResourceManager.GetString("TaskConvert_CopyingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading data patch ähnelt.
        /// </summary>
        internal static string TaskConvert_DownloadFileData {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading fonts ähnelt.
        /// </summary>
        internal static string TaskConvert_DownloadFont {
            get {
                return ResourceManager.GetString("TaskConvert_DownloadFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patching data ähnelt.
        /// </summary>
        internal static string TaskConvert_PatchData {
            get {
                return ResourceManager.GetString("TaskConvert_PatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patching fonts ähnelt.
        /// </summary>
        internal static string TaskConvert_PatchFont {
            get {
                return ResourceManager.GetString("TaskConvert_PatchFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Gold Registry path to:  ähnelt.
        /// </summary>
        internal static string TaskConvert_QstSetReg {
            get {
                return ResourceManager.GetString("TaskConvert_QstSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no change needed ähnelt.
        /// </summary>
        internal static string TaskHook_Ok {
            get {
                return ResourceManager.GetString("TaskHook_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die patching ähnelt.
        /// </summary>
        internal static string TaskHook_Patching {
            get {
                return ResourceManager.GetString("TaskHook_Patching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die validating hook ähnelt.
        /// </summary>
        internal static string TaskHook_Validating {
            get {
                return ResourceManager.GetString("TaskHook_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking out ähnelt.
        /// </summary>
        internal static string TaskMPMap_Checkout {
            get {
                return ResourceManager.GetString("TaskMPMap_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not found, cloning ähnelt.
        /// </summary>
        internal static string TaskMPMap_Cloning {
            get {
                return ResourceManager.GetString("TaskMPMap_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die copying files ähnelt.
        /// </summary>
        internal static string TaskMPMap_CopyFiles {
            get {
                return ResourceManager.GetString("TaskMPMap_CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deleting changes ähnelt.
        /// </summary>
        internal static string TaskMPMap_DirtyDeleting {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! changes in repo, but chosen to keep ähnelt.
        /// </summary>
        internal static string TaskMPMap_DirtyKeep {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have changes in {0}, delete? ähnelt.
        /// </summary>
        internal static string TaskMPMap_ErrDirty {
            get {
                return ResourceManager.GetString("TaskMPMap_ErrDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die found, fetching ähnelt.
        /// </summary>
        internal static string TaskMPMap_Fetch {
            get {
                return ResourceManager.GetString("TaskMPMap_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die latest commit:  ähnelt.
        /// </summary>
        internal static string TaskMPMap_LatestComm {
            get {
                return ResourceManager.GetString("TaskMPMap_LatestComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handling repo:  ähnelt.
        /// </summary>
        internal static string TaskMPMap_Repo {
            get {
                return ResourceManager.GetString("TaskMPMap_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die updating MP maps and scripts ähnelt.
        /// </summary>
        internal static string TaskMPMap_Start {
            get {
                return ResourceManager.GetString("TaskMPMap_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading patch ähnelt.
        /// </summary>
        internal static string TaskUpdate105_DownloadPatch {
            get {
                return ResourceManager.GetString("TaskUpdate105_DownloadPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing external patcher, please follow its UI. ähnelt.
        /// </summary>
        internal static string TaskUpdate105_MsgPatch {
            get {
                return ResourceManager.GetString("TaskUpdate105_MsgPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful:  ähnelt.
        /// </summary>
        internal static string TaskUpdate105_Successful {
            get {
                return ResourceManager.GetString("TaskUpdate105_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing patch, waiting for it to finish... ähnelt.
        /// </summary>
        internal static string TaskUpdate105_WaitForExec {
            get {
                return ResourceManager.GetString("TaskUpdate105_WaitForExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading exe patch ähnelt.
        /// </summary>
        internal static string TaskUpdate106_DownloadFileExe {
            get {
                return ResourceManager.GetString("TaskUpdate106_DownloadFileExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patching exe ähnelt.
        /// </summary>
        internal static string TaskUpdate106_PatchExe {
            get {
                return ResourceManager.GetString("TaskUpdate106_PatchExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History Edition ähnelt.
        /// </summary>
        internal static string TitleConvert {
            get {
                return ResourceManager.GetString("TitleConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install Location ähnelt.
        /// </summary>
        internal static string TitleInstallation {
            get {
                return ResourceManager.GetString("TitleInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S5 Updater ähnelt.
        /// </summary>
        internal static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry ähnelt.
        /// </summary>
        internal static string TitleReg {
            get {
                return ResourceManager.GetString("TitleReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gold ähnelt.
        /// </summary>
        internal static string TitleUpdate {
            get {
                return ResourceManager.GetString("TitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch required ähnelt.
        /// </summary>
        internal static string Txt_AllPatchedNO {
            get {
                return ResourceManager.GetString("Txt_AllPatchedNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch OK ähnelt.
        /// </summary>
        internal static string Txt_AllPatchedOK {
            get {
                return ResourceManager.GetString("Txt_AllPatchedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Mappacks ähnelt.
        /// </summary>
        internal static string Txt_Btn_UpdateMappacks {
            get {
                return ResourceManager.GetString("Txt_Btn_UpdateMappacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert HE to Gold ähnelt.
        /// </summary>
        internal static string Txt_Convert {
            get {
                return ResourceManager.GetString("Txt_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Development Mode ähnelt.
        /// </summary>
        internal static string Txt_DevMode {
            get {
                return ResourceManager.GetString("Txt_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die easy mode ähnelt.
        /// </summary>
        internal static string Txt_EasyMode {
            get {
                return ResourceManager.GetString("Txt_EasyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enabled ähnelt.
        /// </summary>
        internal static string Txt_EnableHook {
            get {
                return ResourceManager.GetString("Txt_EnableHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured, please show at the log. If you don&apos;t know what to do, copy&amp;paste it when asking for help. ähnelt.
        /// </summary>
        internal static string Txt_ErrMsg {
            get {
                return ResourceManager.GetString("Txt_ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die base ähnelt.
        /// </summary>
        internal static string Txt_Extra0 {
            get {
                return ResourceManager.GetString("Txt_Extra0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fogland ähnelt.
        /// </summary>
        internal static string Txt_Extra1 {
            get {
                return ResourceManager.GetString("Txt_Extra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die legends ähnelt.
        /// </summary>
        internal static string Txt_Extra2 {
            get {
                return ResourceManager.GetString("Txt_Extra2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set registry ähnelt.
        /// </summary>
        internal static string Txt_GoldSetReg {
            get {
                return ResourceManager.GetString("Txt_GoldSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install map ähnelt.
        /// </summary>
        internal static string Txt_InstallMap {
            get {
                return ResourceManager.GetString("Txt_InstallMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Txt_Langua {
            get {
                return ResourceManager.GetString("Txt_Langua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  into  ähnelt.
        /// </summary>
        internal static string Txt_MapInto {
            get {
                return ResourceManager.GetString("Txt_MapInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chosen resolution requires Developent mode, enable? ähnelt.
        /// </summary>
        internal static string Txt_QuestEnableDevModeRes {
            get {
                return ResourceManager.GetString("Txt_QuestEnableDevModeRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry already set, override? ähnelt.
        /// </summary>
        internal static string Txt_QuestOverrideReg {
            get {
                return ResourceManager.GetString("Txt_QuestOverrideReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string Txt_SetGold {
            get {
                return ResourceManager.GetString("Txt_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show intro video ähnelt.
        /// </summary>
        internal static string Txt_ShowIntro {
            get {
                return ResourceManager.GetString("Txt_ShowIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show log ähnelt.
        /// </summary>
        internal static string Txt_ShowLog {
            get {
                return ResourceManager.GetString("Txt_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string Txt_TabPageGeneral {
            get {
                return ResourceManager.GetString("Txt_TabPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maps ähnelt.
        /// </summary>
        internal static string Txt_TabPageMaps {
            get {
                return ResourceManager.GetString("Txt_TabPageMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win 10 Fix ähnelt.
        /// </summary>
        internal static string Txt_Update106 {
            get {
                return ResourceManager.GetString("Txt_Update106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update from 1.05 ähnelt.
        /// </summary>
        internal static string Txt_UpdateFrom105 {
            get {
                return ResourceManager.GetString("Txt_UpdateFrom105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update hook ähnelt.
        /// </summary>
        internal static string Txt_UpdateHook {
            get {
                return ResourceManager.GetString("Txt_UpdateHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update MP maps ähnelt.
        /// </summary>
        internal static string Txt_UpdateMP {
            get {
                return ResourceManager.GetString("Txt_UpdateMP", resourceCulture);
            }
        }
    }
}
