//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S5Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold: .
        /// </summary>
        internal static string Lbl_Gold {
            get {
                return ResourceManager.GetString("Lbl_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Lbl_Reso {
            get {
                return ResourceManager.GetString("Lbl_Reso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Gold registry to: .
        /// </summary>
        internal static string Log_RegGold {
            get {
                return ResourceManager.GetString("Log_RegGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dev Mode to: .
        /// </summary>
        internal static string Log_SetDev {
            get {
                return ResourceManager.GetString("Log_SetDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold install location set to: .
        /// </summary>
        internal static string Log_SetGold {
            get {
                return ResourceManager.GetString("Log_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Resolution to: .
        /// </summary>
        internal static string Log_SetReso {
            get {
                return ResourceManager.GetString("Log_SetReso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Status_Invalid {
            get {
                return ResourceManager.GetString("Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Status_Ok {
            get {
                return ResourceManager.GetString("Status_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking out.
        /// </summary>
        internal static string TaskMPMap_Checkout {
            get {
                return ResourceManager.GetString("TaskMPMap_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found, cloning.
        /// </summary>
        internal static string TaskMPMap_Cloning {
            get {
                return ResourceManager.GetString("TaskMPMap_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copying files.
        /// </summary>
        internal static string TaskMPMap_CopyFiles {
            get {
                return ResourceManager.GetString("TaskMPMap_CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting changes.
        /// </summary>
        internal static string TaskMPMap_DirtyDeleting {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! changes in repo, but chosen to keep.
        /// </summary>
        internal static string TaskMPMap_DirtyKeep {
            get {
                return ResourceManager.GetString("TaskMPMap_DirtyKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changes in {0}, delete?.
        /// </summary>
        internal static string TaskMPMap_ErrDirty {
            get {
                return ResourceManager.GetString("TaskMPMap_ErrDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found, fetching.
        /// </summary>
        internal static string TaskMPMap_Fetch {
            get {
                return ResourceManager.GetString("TaskMPMap_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest commit: .
        /// </summary>
        internal static string TaskMPMap_LatestComm {
            get {
                return ResourceManager.GetString("TaskMPMap_LatestComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling repo: .
        /// </summary>
        internal static string TaskMPMap_Repo {
            get {
                return ResourceManager.GetString("TaskMPMap_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating MP maps and scripts.
        /// </summary>
        internal static string TaskMPMap_Start {
            get {
                return ResourceManager.GetString("TaskMPMap_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Location.
        /// </summary>
        internal static string TitleInstallation {
            get {
                return ResourceManager.GetString("TitleInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S5 Updater.
        /// </summary>
        internal static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string TitleReg {
            get {
                return ResourceManager.GetString("TitleReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string TitleUpdate {
            get {
                return ResourceManager.GetString("TitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        internal static string Txt_DevMode {
            get {
                return ResourceManager.GetString("Txt_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy mode.
        /// </summary>
        internal static string Txt_EasyMode {
            get {
                return ResourceManager.GetString("Txt_EasyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set registry.
        /// </summary>
        internal static string Txt_GoldSetReg {
            get {
                return ResourceManager.GetString("Txt_GoldSetReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen resolution requires Developent mode, enable?.
        /// </summary>
        internal static string Txt_QuestEnableDevModeRes {
            get {
                return ResourceManager.GetString("Txt_QuestEnableDevModeRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Txt_SetGold {
            get {
                return ResourceManager.GetString("Txt_SetGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show log.
        /// </summary>
        internal static string Txt_ShowLog {
            get {
                return ResourceManager.GetString("Txt_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update MP maps.
        /// </summary>
        internal static string Txt_UpdateMP {
            get {
                return ResourceManager.GetString("Txt_UpdateMP", resourceCulture);
            }
        }
    }
}
